# Generated by Django 4.2.7 on 2026-05-25 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_loan_penalty_overdue_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='overdue_days',
        ),
    ]
