# Generated by Django 4.2.7 on 2026-04-20 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_loanpayment_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplicationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('default_interest_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('default_loan_duration_months', models.PositiveIntegerField(default=12)),
            ],
            options={
                'verbose_name_plural': 'Loan Application Settings',
            },
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purpose', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('admin_remarks', models.TextField(blank=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('approved_interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('approved_due_date', models.DateField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to='core.member')),
            ],
        ),
    ]
