# Generated by Django 4.2.7 on 2026-05-11 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_loan_enable_fixed_penalty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='loan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='core.loan'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Closed', 'Closed'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
