# Generated by Django 4.2.7 on 2026-05-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_loanapplication_loan_alter_loanapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='enable_fixed_penalty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='enable_late_fee_per_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='enable_percentage_penalty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='fixed_penalty_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='grace_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='late_fee_per_day',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='penalty_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='percentage_penalty_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='pedi',
            name='enable_fixed_penalty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedi',
            name='enable_late_fee_per_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedi',
            name='enable_percentage_penalty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedi',
            name='fixed_penalty_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedi',
            name='grace_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pedi',
            name='late_fee_per_day',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedi',
            name='penalty_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedi',
            name='percentage_penalty_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
