# Generated by Django 4.2.7 on 2026-05-19 00:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_payment_enable_fixed_penalty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberpedi',
            name='membership_start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='memberpedi',
            name='membership_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberpedi',
            name='joined_month',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
