# Generated by Django 4.2.7 on 2026-05-19 00:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_memberpedi_membership_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplicationsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplicationsettings',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
