# Generated by Django 4.2.7 on 2026-05-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_memberpedi_exit_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanapplicationsettings',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Loan Application Settings'},
        ),
        migrations.AddField(
            model_name='memberpedi',
            name='admin_exit_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberpedi',
            name='admin_exit_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='memberpedi',
            name='member_exit_request_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='memberpedi',
            name='member_exit_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memberpedi',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Exit Requested', 'Exit Requested'), ('Completed', 'Completed'), ('Defaulted', 'Defaulted'), ('Exited', 'Exited')], default='Active', max_length=20),
        ),
    ]
