# Generated by Django 4.2.7 on 2026-04-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_loantransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanpayment',
            name='payment_method',
            field=models.CharField(choices=[('Online', 'Online'), ('Cash', 'Cash')], default='Online', max_length=20),
        ),
    ]
